### ISSUE TITLE
Link to sass api on ReadMe navigates to 404 page

### ISSUE THREAD

**Issue by razorsyntax** [PredixDev/px-typography-design#10]
# Submit an Issue

[API Link](http://predixdev.github.io/px-typography-design/sassdoc/) takes you to a 404 page.
Link: http://predixdev.github.io/px-typography-design/sassdoc/

## Expected behavior and actual behavior:

Expected: Navigates to API page.

Actual: Navigates user to 404 page.

## Steps to reproduce the problem:

1) Click the link.
2) Verify 404 page

**Comment by evanjd** [comment]
Thanks, link updated!
