### ISSUE TITLE
Files missing in latest version

### ISSUE THREAD

**Issue by ghost** [PredixDev/px-typography-design#3]
I've recently updated to the latest version of this component, but it seems some of the files are now missing:
GEInspMd.eot
GEInspMdIt.eot

It looks now that there is only either the Serif or Sans family, the third one is gone. 

Is this by design?

**Comment by mdwragg** [comment]
Hi, this is by design.

See release here: https://github.com/PredixDev/px-typography-design/releases/tag/v1.0.0

**Comment by randyaskin** [comment]
@avnish19 this coincides with the September 8th GE brand refresh announced [here](http://my.ge.com/card/ge-news/6100596) (accessible by GE internal only) where Sans was announced as our primary font.
