### ISSUE TITLE
Confusion on demo page

### ISSUE THREAD

**Issue by gstroup** [PredixDev/px-typography-design#4]
https://www.predix-ui.com/#/css/px-typography-design/

The page shows two different ways to import the file.  Near the top it says:
`@import "px-typography-design/_base.typography.scss";`

Later on, it says incorrectly:
`@import "px-typography-design/_settings.typography.scss";`

**Comment by katemenkhaus** [comment]
It is supposed to be `@import "px-typography-design/_base.typography.scss";`
I will fix it in the demo page. 
Thank you for bringing this to our attention.

**Comment by katemenkhaus** [comment]
This has been fixed with v1.2.6
