### ISSUE TITLE
Px fonts security vulnerability

### ISSUE THREAD

**Issue by arcpato** [PredixDev/px-typography-design#6]
Hi, 

We are running into some issues with Predix fonts not passing the sonarQube quality code checks.
 
Basically we are getting some Security Vulnerability bugs associated to the px fonts. This is the issue as seen in sonarQube:
 
```
Noncompliant Code Example
@font-face {
  src: url("//myfont");
}
Compliant Solution
@font-face {
  src: url("https://myfont");
}
```

And here is an example of the noncompliant url:
(All fonts from PX are coming in with url’s like this…)
 
`src: url("//dzlpbrbc7yvq0.cloudfront.net/predixdev/fonts/1.0.0/GEInspiraSans-Regular-v01.eot?#iefix") format("embedded-opentype"), url("//dzlpbrbc7yvq0.cloudfront.net/predixdev/fonts/1.0.0/GEInspiraSans-Regular-v01.woff") format("woff"), url("//dzlpbrbc7yvq0.cloudfront.net/predixdev/fonts/1.0.0/GEInspiraSans-Regular-v01.ttf") format("truetype"), url("//dzlpbrbc7yvq0.cloudfront.net/predixdev/fonts/1.0.0/GEInspiraSans-Regular-v01.svg#GE Inspira Sans") format("svg"); }`
 
Seems to be related to this line on the `_base.typography.scss` file:
 
`$inuit-webfont-path: '//dzlpbrbc7yvq0.cloudfront.net/predixdev/fonts/1.0.0' !default;`

The concern is again that this path is not a safe/compliant way of calling the resource.

**Comment by mdwragg** [comment]
A couple of thoughts @arcpato:

1. Can we have some attribution to why specifying the protocol vs. using a protocol-relative URL is desirable?

2. Given that, it sounds like you're closest to the metal in testing this out, can we have a PR that you've tested with the protocol-specific URL against the CDN deployment of the fonts.

Thanks!

(please feel free to mention devs here on your team to continue the conversation).

cc @PredixDev/px

**Comment by mdwragg** [comment]
@212398360 ^^

**Comment by arcpato** [comment]
@212398360

**Comment by arcpato** [comment]
@spachalla12 See above
