### ISSUE TITLE
Unable to load fonts saying forbidden

### ISSUE THREAD

**Issue by ramanav** [PredixDev/px-typography-design#7]
# Submit an Issue

Hi,

Thanks for helping us improve the Predix UI platform by submitting an issue.

Before you begin, please check the list of existing issues to avoid submitting a duplicate issue.

To help us solve this issue as fast as possible, please fill out the following sections:

## Expected behavior and actual behavior:
GE fonts load load/render in UI without any issues.
## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
"version": "1.2.6",
## Screenshots (_optional, but very helpful_):
{
 "name": "px-typography-design",
  "version": "1.2.6",
  "homepage": "https://github.com/PredixDev/px-typography-design.git",
  "authors": [
    "General Electric"
  ],
  "description": "Base typographic styles for Predix UI",
  "main": "_base.typography.scss",
  "keywords": [
    "px",
    "sass",
    "typography"
  ],

![1222](https://user-images.githubusercontent.com/23207396/36308574-4475de1e-1347-11e8-8d2e-cdfe401300ce.png)

## Code examples help us better understand the issue - follow the appropriate codepen for the component by going to https://predix-ui.com, finding the component in question, and clicking on the pencil icon under the demo.
Once you've created your code example, you can save it under a new url.
Please note that you should NOT use the same methods for production as the ones used in codepen - these methods are not production ready.

**Comment by mdwragg** [comment]
Hi,

It appears some one pulled the rug out under our feet on the CDN...

@baspete Do you know who maintains those S3 buckets these days? Thanks.

**Comment by mdwragg** [comment]
@ramanav, do you use px-theme in your application (https://github.com/PredixDev/px-theme)?

**Comment by ramanav** [comment]
@mdwragg, yes we use px-theme 2.0 but not latest version. We use px-theme which supports polymer 1.0 components.

**Comment by mdwragg** [comment]
@ramanav - can you switch to the latest px-theme and load https://github.com/PredixDev/px-theme/blob/master/px-theme-local-fonts-styles.html

like:
```
<link async rel="import" href="bower_components/px-theme/px-theme-local-fonts-styles.html"/>
<style is="custom-style" include="px-theme-local-fonts-styles"></style>
```

This will load fonts from a local dependency, not from the CDN.

**Comment by ramanav** [comment]
@mdwragg, you mean px-theme 3.0. No we cannot update to new theme because there are lot of things we need to update including polymer also. So we cannot update to latest theme. Is there any alternative way.

**Comment by mdwragg** [comment]
px-theme works with Polymer 1 and 2.

**Comment by baspete** [comment]
@mdwragg Last I checked it was Jeremiah Carlson, the DevOps lead for APM.

**Comment by mdwragg** [comment]
Thanks @baspete. 💯 Will follow up.

**Comment by mdwragg** [comment]
Fixed. Patched in Cirrus and pre-cirrus versions of px-theme, px-dark-theme and px-typography-design.
